# Generated by Django 4.1.2 on 2022-10-20 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_rideevent_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideevent',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_events', to='project.ride'),
        ),
    ]
